path: "/content/gdrive/MyDrive/SafeSkies/training/" # dataset root dir
train: data/train/images # train images (relative to 'path')
val: data/validation/images # val images (relative to 'path')

# Classes
names:
    0: balloon
