path: "/content/gdrive/MyDrive/SafeSkies/balloon_detection/" # dataset root dir
train: data/train/images # train images (relative to 'path')
val: data/test/images # test images (relative to 'path')

# Classes
names:
    0: balloon
